// @ts-expect-error backendApp is generated by `npm run build:backend:vercel` before Next.js builds.
import backendApp from "../../backend/dist-cjs/api/index.js";

type RequestLike = {
  url?: string;
};

type ResponseLike = object;

export default function handler(request: RequestLike, response: ResponseLike) {
  if (request.url) {
    request.url = request.url.replace(/^\/api\/backend(?=\/|$)/, "/api") || "/api";
  }

  return backendApp(request as never, response as never);
}
