"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.apiRouter = void 0;
const express_1 = require("express");
const require_admin_auth_js_1 = require("../middlewares/require-admin-auth.js");
const apartment_routes_js_1 = require("../modules/apartments/apartment.routes.js");
const area_routes_js_1 = require("../modules/areas/area.routes.js");
const auth_routes_js_1 = require("../modules/auth/auth.routes.js");
const contact_routes_js_1 = require("../modules/contacts/contact.routes.js");
const land_listing_routes_js_1 = require("../modules/land-listings/land-listing.routes.js");
const media_routes_js_1 = require("../modules/media/media.routes.js");
const post_routes_js_1 = require("../modules/posts/post.routes.js");
const project_routes_js_1 = require("../modules/projects/project.routes.js");
const rental_routes_js_1 = require("../modules/rentals/rental.routes.js");
exports.apiRouter = (0, express_1.Router)();
exports.apiRouter.use("/auth", auth_routes_js_1.authRouter);
exports.apiRouter.use("/areas", area_routes_js_1.areaRouter);
exports.apiRouter.use("/apartments", apartment_routes_js_1.apartmentRouter);
exports.apiRouter.use("/contacts", contact_routes_js_1.contactRouter);
exports.apiRouter.use("/projects", project_routes_js_1.projectRouter);
exports.apiRouter.use("/land-listings", land_listing_routes_js_1.landListingRouter);
exports.apiRouter.use("/rentals", rental_routes_js_1.rentalRouter);
exports.apiRouter.use("/posts", post_routes_js_1.postRouter);
exports.apiRouter.use("/media", require_admin_auth_js_1.requireAdminAuth, media_routes_js_1.mediaRouter);
